config/routes.rb
Rails.application.routes.draw do
  get 'carts/show'
  devise_for :users
  root to: 'pages#home'
  get '/cooks', to: 'pages#cooks'
  get '/profile', to: 'pages#profile'
  get "/become_cook", to: "pages#apply"
  get '/confirmation', to: 'orders#confirmation'
  get '/calendar', to: 'pages#calendar'
  get '/users/:id/update', to: 'pages#update', as: :update_user

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :week_days, only: [:new, :create]
  resources :meals do
    resources :reviews, only: [:new, :create]
    resources :items, only: [:new, :create]
    resources :cooks, only: [:show]
  end

  resources :orders, only: [:create, :show] do
    resources :payments, only: [:new, :create]
    resources :items, only: [:destroy]
  end

  resources :dashboard, only: :index

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @week_day = WeekDay.new
    @today = Date.today
    @my_meals = policy_scope(Meal).where(cook_id: current_user.id)
    authorize @my_meals

    @orders = policy_scope(Order).all
    authorize @orders
    @my_orders = []
    @orders.each do |order|
      if order.user == current_user
        @my_orders << order
      end
    end
    @my_orders

    @items = policy_scope(Item).all
    @items_from_cook = []
    @items.each do |item|
      if item.meal.cook == current_user
        @items_from_cook << item
      end
    end
    @items_from_cook
  end

end

app/views/dashboard/_cook_table.html.erb
<table class="table-dashboard">
  <caption>Orders</caption>
  <thead>
    <th>Ordered By</th>
    <th>Meal</th>
    <th>Doses</th>
    <th>Date</th>
    <th>Price</th>
    <th>Status</th>
    <th></th>
  </thead>
  <tbody>
    <% @items_from_cook.each do |item| %>
      <tr>
        <td><%= item.order.user.first_name %></td>
        <td><%= item.meal.name %></td>
        <td><%= item.doses %></td>
        <td><%= item.order.created_at.strftime('%d %b %Y') %></td>
        <td><%= item.item_price %>€</td>
        <td id="order_status"><%= item.order.status.capitalize %></td>
        <% if item.order.status == 'paid' %>
          <td><button id='btn_status'>Mark as delivered</button></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>


<script>
  const button = document.getElementById('btn_status');
  let status = document.getElementById('order_status');
  button.addEventListener('click', (event) => {
    status.innerText = 'Delivered';
    button.style.display = 'none';
  })
</script>

app/views/dashboard/_drag_card.html.erb
<div class="col-xs-12 col-sm-6 col-md-4">
  <div class="drag_card" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.3) 0%, rgba(0,36,61,0.4) 50%), url('<%= meal.photo %>')">
    <div class="description">
      <h4><%= meal.name %></h4>
    </div>
    <div class="drag_card-footer">
      <p><%= meal.price %>€</p>
    </div>
  </div>
</div>

app/views/dashboard/_user_table.html.erb
<% @my_orders.each do |order| %>
  <% if order.status != 'pending' %>
    <table class="table-dashboard-user">
      <caption style="text-align: center; font-size: 16px;">
        <span>Order #<%= order.id %></span> |
        <span>Date: <%= order.created_at.strftime('%d %b %Y') %></span> |
        <span>Status: <%= order.status.capitalize %></span>
      </caption>
      <thead>
        <th>Meal</th>
        <th>Cook</th>
        <th>Doses</th>
        <th>Price</th>
      </thead>
      <tbody>
        <% order.items.each do |item| %>
          <tr>
            <td><%= item.meal.name %></td>
            <td><%= link_to item.meal.cook.first_name, meal_cook_path(item, item.meal) %></td>
            <td><%= item.doses %></td>
            <td><%= item.meal.price * item.doses %>€</td>
          </tr>
        <% end %>
          <tr class="table-row">
            <td></td>
            <td></td>
            <td></td>
            <td>Total: <strong> <%= order.total_price %>€</strong></td>
          </tr>
      </tbody>
    </table>
  <% end %>
<% end %>

app/views/dashboard/index.html.erb
<div style="margin: 60px 130px;">
  <ul class="nav nav-tabs">
    <% if current_user.cook_status == 1 %>
      <li class="active"><a class='detail' data-toggle="tab" href="#meals">Meals</a></li>
      <li><a data-toggle="tab" href="#orders">Orders</a></li>
    <% end %>
  </ul>

  <div class="tab-content">
    <% if current_user.cook_status == 1 %>

      <div id="meals" class="tab-pane fade in active">
        <div class="meals-submit">
          <%= link_to "Submit a meal for approval", new_meal_path %>
        </div>

        <div class="meals-repository">
          <h2>My Meals</h2>
          <h4>Approved Meals</h4>
        </div>

        <div class="row">
          <% @my_meals.each do |meal| %>
          <%= link_to render("drag_card", meal: meal), meal_path(meal) %>
          <% end %>
        </div>


        <h2 class="meals-repository">Plan the schedule for the next week:</h2>
        <%#= link_to "Create a new schedule",  new_week_day_path, class: "btn btn-danger" %>
        <div class="table-scroll">
          <table class="table">
          <thead>
            <% (0..6).each do |x| %>
              <% @selected_day = (@today + x) %>
              <th class='text-center'><%= @selected_day.strftime('%A') %> - <%= @selected_day.strftime('%x') %></th>
            <% end %>
          </thead>
          <tbody>
            <tr>
              <% (0..6).each do |x| %>
                <% @selected_day = (@today + x) %>
                <% if current_user.week_days.where(date: @selected_day).empty? %>
                  <td><%= render "week_days/form_week_day", form: [@my_meals, @selected_day] %></td>
                <% else%>
                  <td>
                    <div class="col-md-12">
                      <div class="submited-card">
                        <div class="submited-card-title">
                          <% meal_name = current_user.week_days.where(date: @selected_day)[0].meal.name %>
                          <h2><%= "#{meal_name} was submitted" %></h2>
                          <hr>
                          <% @weekday = current_user.week_days.where(date: @selected_day)[0] %>
                          <p>Orders until:</p>
                          <p> <%= @weekday.last_order_time.strftime("%Hh%M") %></p>
                          <hr>
                          <p> Pick up time:   </p>
                          <p>  <%= @weekday.pick_up_time_start.strftime("%Hh%M")%> - <%= @weekday.pick_up_time_end.strftime("%Hh%M")%> </p>
                        </div>
                     </div>
                   </div>
                  </td>
               <% end %>
             <% end %>
           </tr>
         </tbody>
        </table>
        </div>
      </div>

      <div id="orders" class="tab-pane fade">
        <div class="row">
          <%= render 'cook_table', items_from_cook: @items_from_cook %>
        </div>
      </div>

    <% else %>

      <div class="row">
        <h4 style="text-align: center">My Orders</h4>
        <%= render 'user_table', my_orders: @my_orders %>
      </div>

    <% end %>
  </div>
</div>