config/routes.rb
Rails.application.routes.draw do
  get 'carts/show'
  devise_for :users
  root to: 'pages#home'
  get '/cooks', to: 'pages#cooks'
  get '/profile', to: 'pages#profile'
  get "/become_cook", to: "pages#apply"
  get '/confirmation', to: 'orders#confirmation'
  get '/calendar', to: 'pages#calendar'
  get '/users/:id/update', to: 'pages#update', as: :update_user

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :week_days, only: [:new, :create]
  resources :meals do
    resources :reviews, only: [:new, :create]
    resources :items, only: [:new, :create]
    resources :cooks, only: [:show]
  end

  resources :orders, only: [:create, :show] do
    resources :payments, only: [:new, :create]
    resources :items, only: [:destroy]
  end

  resources :dashboard, only: :index

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
  <div class="footer">
    <h1><b>FOOD NEXT DOOR</b></h1>
  <div class="footer-content">
    <div class="footer-column">
      <h4><B>DOWNLOAD THE APP</B></h4>
        <p><img src="https://www.buderus.com/ch/media/central_pool/fachkunden/cat_460x460/apps/cat_app-store-google-play_1_2ColumnSmallMediaText.png" alt="" width= "220px"></p>
    </div>
    <div class="footer-column">
      <h4></h4>
    </div>
    <div class="footer-column">
      <h4></h4>
    <div class="footer-column">
      <h4><b>CONTACT US</b></h4>
          <p>hello@foodnextdoor.com</p>
          <p>Become a cook</p>
    </div>
    </div>
    <div class="footer-column">
      <h4><b>ABOUT</b></h4>
        <p>How we work</p>
        <p>Our philosophy</p>
    </div>
    <div class="footer-column">
      <h4><b>HELP</b></h4>
    </div>
  </div>
  <div class="footer-symbols text-right">
    <p><i class="fab fa-facebook-f"></i> <i class="fab fa-instagram"></i> <i class="fab fa-twitter-square"></i>
  </p>
  </div>
</div>

app/views/shared/_info_window.html.erb
<div class="info-window">
  <h4> <%= item.meal.name %></h4>
  <p>Cooked by <strong><%= item.meal.cook.first_name %></strong></p>
    <div class="info-image" style="background: url(<%= item.meal.photo %>)">
    </div>
    <div class="info-description">
      <%= item.meal.description %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <div class="logo">
    <%= link_to meals_path, class: "navbar-wagon-brand" do %>
      <%= image_tag "logo.png", height: 50 %>
    <% end %>
      <span id="brand"><h3>Food Next Door</h3></span>
  </div>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">



    <% if user_signed_in? %>

    <!-- Links when logged in -->
    <% if current_user.meals.empty? && current_user.cook_status == 0 %>
      <%= link_to "Apply to be a cook", become_cook_path, class: "navbar-wagon-item navbar-wagon-link"  %>
    <% end %>

    <%#= link_to "Host", "#", class: "navbar-wagon-item navbar-wagon-link" %>


    <!-- Avatar with dropdown menu -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <span class="navbar-wagon-item-name">Hello <strong><%= current_user.first_name %>!</strong></span>
        <% if current_user.photo.model[:photo] == nil %>
          <% if current_user.photo_fake.nil? %>
          <%= image_tag "https://collaborativecbt.com/wp-content/uploads/2016/12/default-avatar.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown"%>
          <% else %>
           <%= image_tag current_user.photo_fake, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown"%>
          <% end %>
        <% else %>
          <%= cl_image_tag current_user.photo, width: 150, height: 150, crop: :thumb, gravity: :face, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown"%>
        <% end %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to edit_user_registration_path do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to dashboard_index_path do %>
            <i class="fas fa-utensils"></i>  <%= t(".settings", default: "Dashboard") %>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
    <div class="navbar-wagon-cart">
      <% if current_user.orders.empty?  %>
      <% elsif current_user.orders.last.status == "pending" %>
        <%= link_to order_path(current_user.orders.last) do %>
        <i class="fas fa-shopping-bag"></i>
        <div class="number-of-articles">
          <%= current_user.orders.pending.last.items.length %>
        </div>
        <% end %>
      <% end %>
    </div>

    <% else %>
    <!-- Login link (when logged out) -->
    <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>



  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>