config/routes.rb
Rails.application.routes.draw do
  get 'carts/show'
  devise_for :users
  root to: 'pages#home'
  get '/cooks', to: 'pages#cooks'
  get '/profile', to: 'pages#profile'
  get "/become_cook", to: "pages#apply"
  get '/confirmation', to: 'orders#confirmation'
  get '/calendar', to: 'pages#calendar'
  get '/users/:id/update', to: 'pages#update', as: :update_user

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :week_days, only: [:new, :create]
  resources :meals do
    resources :reviews, only: [:new, :create]
    resources :items, only: [:new, :create]
    resources :cooks, only: [:show]
  end

  resources :orders, only: [:create, :show] do
    resources :payments, only: [:new, :create]
    resources :items, only: [:destroy]
  end

  resources :dashboard, only: :index

end

app/models/meal.rb
class Meal < ApplicationRecord

  include PgSearch
  pg_search_scope :search_by_name_and_address,
    against: [ :name, :address ],
    using: {
      tsearch: { prefix: true }
    }

    pg_search_scope :search_by_address,
    against: [ :address ],
    using: {
      tsearch: { prefix: true }
    }

  scope :price_cents, -> (max_price) { where("price_cents < ?", max_price) }

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?


  has_many :items, dependent: :destroy
  has_many :users, through: :items
  has_many :reviews, dependent: :destroy
  has_many :line_items, dependent: :destroy
  has_many :week_days
  belongs_to :cook, class_name: 'User', optional: true
  monetize :price_cents
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  before_action :set_meals, only: [:edit, :destroy, :update]
  skip_before_action :authenticate_user!, only: [ :index, :show]
  #layout 'map', only: :index

  def index
    @meals = policy_scope(Meal).order(created_at: :desc)
    authorize @meals
    # Query location in search bar
    @meals = Meal.near(params[:location], 10, order: 'distance') if params[:location].present?
    @max_price_cents = 3000
    @meals = @meals.price_cents(params[:price]) if params[:price].present?
    # @max_distance = 10
    @meals = meals_of_the_day(@meals)
    # Markers placement, icons and info window
    iconmarker = 'http://maps.google.com/mapfiles/ms/icons/green-dot.png'
    @markers = @meals.map do |meal|
      {
        lat: meal.latitude,
        lng: meal.longitude,
        icon: iconmarker,
        infoWindow: {
          content: meal.name
        }
      }
    end

  end

  def show
    @item = Item.new
    @meal = Meal.find(params[:id])
    @meal.week_days.select{|item| item[:date] == Date.today}
    authorize @meal
  end

  def new
    @meal = Meal.new
    authorize @meal
  end

  def create
    @meal = Meal.new(meal_params)
    @meal.cook = current_user
    @meal.address = current_user.address
    #raise
    authorize @meal
    if @meal.photo.nil?
      @meal.photo = "https://img.theculturetrip.com/wp-content/uploads/2014/10/shutterstock_409496941.jpg"
    end
    if @meal.save
      redirect_to dashboard_index_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @meal.update(meal_params)
    redirect_to meal_path(@meal)
  end

  def destroy
    @meal.destroy
    redirect_to meals_path
  end


  private
  def meals_of_the_day(all_meals)
  # This was created because we needed to know the meals where the week_day == Date.today
  # We needed to create a cicle inside of a cicle because we have a 1:N relationship and it was supose to be N:N
  # We have that 1 meal have N weekdays and 1 weekday have only 1 meal(That is not true. It is only true for one cook!)
  # One cook can only assign one meal per day.
  @filtered_meals = []
    all_meals.each do |meal|
      meal.week_days.each do |weekday|
        if weekday.date == Date.today && weekday.last_order_time > Time.now
          @filtered_meals << weekday.meal
        end
      end
    end
    @filtered_meals
  end



  def meal_params
    params.require(:meal).permit(:name, :description, :address, :price, :grams_per_dose, :ingredients)
  end

  def set_meals
    @meal = Meal.find(params[:id])
    authorize @meal
  end

end

app/views/meals/_card.html.erb
<div class="col-xs-12 col-sm-6 col-lg-4" id="cards-section">
  <div class="card">
    <%= link_to meal_path(meal) do %>
      <div class="card-picture"
          style="background: url('<%= meal.photo %>')"></div>
      <div class="description">
        <div>
          <p><%= meal.name %></p>
          <p class="sub"><%= meal.description %></p>
        </div>
      </div>
    <% end %>

      <%# weekday_meal = meal.week_days.where(date: Date.today)[0] %>
      <div class="card-footer">
        <div><p><%= meal.price %>€</p></div>
        <div class="card-time">pick-up time: <%#= weekday_meal.pick_up_time_start.strftime('%Hh%M') %> / <%#= weekday_meal.pick_up_time_end.strftime('%Hh%M') %></div>
        <div><i class="fas fa-cart-plus fa-lg"></i></div>
      </div>
    </div>
</div>

<script>
  function decrease() {
    let val = document.querySelector(".val");
    if(parseInt(val.value) > parseInt(val.min)) {
      val.value = parseInt(val.value) - 1;
    }
    return val;
  }
  function increase() {
    let val = document.querySelector(".val");
    if(parseInt(val.value) < parseInt(val.max)) {
      val.value = parseInt(val.value) + 1;
    }
    return val;
  }
</script>

app/views/meals/_card_list.html.erb
<% meals.each do |meal| %>
  <%= render meal %>
<% end %>

app/views/meals/_filters.html.erb
<%= form_tag('/meals', method: :get, class: 'form-inline', remote: true) do %>
    <div class="filter">
      <label for="price" id="price_change" >Price: <%= @max_price_cents / 100 %>€</label>
      <input id="price" name="price" type="range" min="0" max="<%= @max_price_cents%>" value="<%= @max_price_cents %>" onchange="changePrice(this.value);" >
    </div>
    <div class="filter-validation-button">
      <input type="submit" value="Apply filters" id="filter-button">
    </div>
<% end %>

app/views/meals/_form.html.erb
<%= simple_form_for(@meal) do |f| %>

<div class="col-md-6 col-md-offset-3">
  <div class="form-body">
    <div class="form-inputs form-control-lg">
      <div class="form-details">
        <h4 style= "border-bottom: 0.5px dotted gray;padding-bottom: 10px;">Meal Details</h4>
       <div class="form-inputs" style="color: black">
      <%= f.input :name, placeholder: 'Enter name', label: false, input_html: { class: 'recognitionStylingName'}%>
        <%= f.input :description,  input_html: { class: 'detailStyling'}, label_html: { class: 'detailLabelStyling'}%>
        <%= f.input :ingredients,  input_html: { class: 'detailStyling'}, label_html: { class: 'detailLabelStyling'}%>
      </div>
        <div class="form-inline">
        <%= f.input :grams_per_dose, class: 'width', input_html: { class: 'detailStylingInline'}, label_html: { class: 'detailLabelStyling'}; %>
        <%= f.input :price, label: 'Price €', class: "width", input_html: { class: 'detailStylingInline', style: "width: 100%"}, label_html: { class: 'detailLabelStyling'};%>
        </div>
  <div class="form-actions flexing-box">
    <%= f.button :submit, class: "btn btn-primary" %>
    <%= link_to "Back", meals_path, class: "btn btn-default" %>
  </div>
</div>
    </div>
  </div>


<% end %>
</div>

app/views/meals/_map.html.erb
<div id="map" data-markers="<%= @markers.to_json %>">

</div>

app/views/meals/_meal.html.erb
<div class="col-xs-12 col-sm-6 col-lg-4 js-card">
  <div class="card">
    <%= link_to meal_path(meal) do %>
      <div class="card-picture"
          style="background: url('<%= meal.photo %>')"></div>
      <div class="card-title">
        <div>
          <p><%= meal.name %></p>
        </div>
      </div>
    <% end %>

      <% weekday_meal = meal.week_days.where(date: Date.today)[0] %>
      <div class="card-footer">
        <div><p><%= meal.price %>€</p></div>
        <div class="card-time"><span class="sub">pick-up time</span> <%= weekday_meal.pick_up_time_start.strftime('%Hh%M') %> / <%= weekday_meal.pick_up_time_end.strftime('%Hh%M') %></div>
        <div><i class="fas fa-clock fa-lg"></i></div>
      </div>
    </div>
</div>

<script>
  function decrease() {
    let val = document.querySelector(".val");
    if(parseInt(val.value) > parseInt(val.min)) {
      val.value = parseInt(val.value) - 1;
    }
    return val;
  }
  function increase() {
    let val = document.querySelector(".val");
    if(parseInt(val.value) < parseInt(val.max)) {
      val.value = parseInt(val.value) + 1;
    }
    return val;
  }
</script>

app/views/meals/_search.html.erb
    <form action="/meals" method="get" id="content">

      <% if !current_user.nil? %>
        <input type="text" name="location" id="search" class="autocomplete animated-search-bar", placeholder=<%= current_user.address  %>>
      <% else %>
        <input type="text" name="location" id="search" class="autocomplete animated-search-bar", placeholder="Insert address">
      <% end %>

        <button type="reset" id="search-button" class="search"><%= image_tag("location.png", width: '35', height: '35')%></button>
        <div class="address-change"><i class="fas fa-angle-left"></i>  Change address</div>
    </form>




<script>
  const searchButton = document.querySelector(".search");
  const input = document.querySelector('#search');
  const expandForm = (element) => {
    searchButton.classList.toggle("close");
    input.classList.toggle("square");
    if (searchButton.classList.contains("close")) {
      input.focus();
    } else {
      input.blur();
    }
  };
  document.getElementById("search-button").addEventListener("click", expandForm);
</script>

app/views/meals/edit.html.erb
<div class="food-wrapper">
  <div class="container">

  <h1 class="text-center">
    Edit Meals
  </h1>
    <%= render "form", meal: @meal  %>
</div>
</div>

app/views/meals/index.html.erb
<!-- search bar and map button -->

<div class="wrapper-search flexing-stuff">
  <div class="">
    <%= render "search" %>
  </div>

  <div class="right-part-search flexing-stuff">
    <%= render 'filters' %>
    <div class="switch-button">
      <p class="switch-text">Show Map</p>
      <label class="switch">
        <input type="checkbox" id="show-map">
        <span class="slider round"></span>
      </label>
    </div>
  </div>
</div>

<!-- cards and map -->

<div class="wrapper">
  <div class="cards-container">
    <%= render @meals%>
  </div>






  <div id="map-container">
    <%= render 'map' %>
  </div>

</div>

<script>
  const filterButton = document.getElementById('filter-button');
  const slider = document.getElementById('price_change');
  function changePrice(value) {
    slider.innerHTML='Price < '+ Math.round(value / 100) +'€';
    filterButton.click();
  }
</script>

<script>
  const map = document.getElementById('map');
  const mapContainer = document.getElementById('map-container');
  const button = document.getElementById('show-map');
  window.isMapOpen = true;
  const hideElement = (element) => {
    if (element.style.display === "none") {
      element.style.display = "block";
      window.isMapOpen = true;
    } else {
      element.style.display = "none";
      window.isMapOpen = false;
    }
  }
  const switchClasses = (element, class1, class2) => {
      element.classList.toggle(class1);
      element.classList.toggle(class2);
    }

  button.addEventListener('click', (event) => {
  var cards = document.querySelectorAll('.js-card');
    hideElement(map);
    hideElement(mapContainer);
    cards.forEach(function(el) {
      switchClasses(el, 'col-lg-4', 'col-lg-3');
    });
  })

</script>

app/views/meals/index.js.erb
var newCards = document.querySelectorAll('.js-card');
function refreshList(innerHTML) {
  document.querySelector('.cards-container').innerHTML = innerHTML;
}
// store meals in variable
var mealsHTML = '<%= j render @meals %>'

function refreshMap(innerHTMLMap) {
  const newMap = document.getElementById('map-container');
  newMap.innerHTML = innerHTMLMap;
}

refreshMap('<%= j render "map" %>');
document.app.initMap(document.getElementById('map'));
  if (!window.isMapOpen) {
    mealsHTML = mealsHTML.replace(/col-lg-4/g, 'col-lg-3')
  }
  console.log(mealsHTML);
  refreshList(mealsHTML);


console.log(window.isMapOpen);

app/views/meals/my_meals.hmtl.erb
my_meals.hmtl.erb

app/views/meals/new.html.erb
<div class="food-wrapper">
  <div class="container">
      <h1 class="text-center" style="font-weight: lighter;"> <strong>Add a new meal</strong></h1>
      <%= render "form", form: @meal %>
  </div>
</div>

app/views/meals/show.html.erb
<div class="meal-banner" style="background-image: url('<%= @meal.photo %>');"></div>

<div class="show">

<!--   <div class="main-container"> -->


    <div class="left-section">
      <div class="meal-header">
        <h4>
          <%= @meal.name %>
          <% if current_user == @meal.cook %>
          <%= link_to edit_meal_path do %>
          <i class="fas fa-pencil-alt fa-l"></i>
          <% end %>
          <%= link_to meal_path, method: :delete, data: {confirm: 'Are you sure?'} do %>
          <i class="fas fa-trash-alt fa-l"></i>
          <% end %>
          <% end %>
          <div class="meal-cook">

            <div class="more-about-cook text-center">
            <% if @meal.cook.photo.model[:photo] == nil %>
            <%= image_tag @meal.cook.photo_fake, id: "navbar-wagon-menu", "data-toggle" => "dropdown"%>
            <% else %>
            <%= cl_image_tag @meal.cook.photo, width: 160, height: 160, crop: :thumb, gravity: :face, class: "avatar-review", id: "navbar-wagon-menu", "data-toggle" => "dropdown"%>
            <% end %>
            <%= link_to  meal_cook_path(@meal) do %>

              <p> More about <br>
             <%= "#{@meal.cook.first_name}" %></p>
            </div>
            <% end%>


          </div>

        </h4>
        <p><strong>Price:</strong> <%= @meal.price %>€</p>
      </div>

    <% weekday_meal = @meal.week_days.where(date: Date.today)[0] %>
      <div class="meal-time">
        <% if weekday_meal.nil? %>
        <p>Today this meal is not available</p>
        <% else %>
        <p><strong>Pickup time: </strong><%= weekday_meal.pick_up_time_start.strftime('%Hh%M') %> - <%= weekday_meal.pick_up_time_end.strftime('%Hh%M') %></p>
        <% end %>
      </div>
      <div class="meal-info">
        <p><%= @meal.description %></p>
        <h5>Ingredients</h5>
        <p><%= @meal.ingredients %></p>
        <h5>Portion</h5>
        <p><%= @meal.grams_per_dose %>g</p>
      </div>

<!--     <div>
      <h4>Get to know the Cook:</h4>
      <p>Name: <%= @meal.cook.first_name %>  <%= @meal.cook.last_name %></p>
      <p>Contact datails: <%= @meal.cook.email %></p>
      <p>Pick up food address: <%= @meal.cook.address %></p>
    </div> -->
    <div class="meal-footer">
      <% if !weekday_meal.nil? %>
      <div class="meal-dose">
        <%= simple_form_for [@meal, @item] do |f| %>
        <div class="form-actions">
          <i class="fas fa-minus" onclick="decrease()"></i>
          <input name="item[doses]" type="number" min="1" max="<%= weekday_meal.doses %>" value="1" class="val" id="item_doses" readonly>
          <i class="fas fa-plus" onclick="increase()"></i>
          <%#= f.button :submit, 'Add to Cart', class: "button" %>
          <input type="submit" name="commit" value="Add to Cart" class="button" data-toggle="modal" data-target="#exampleModal">
        </div>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>

<!-- </div> -->

<% ratings = [] %>
<% @meal.reviews.each do |review| %>
<% ratings << review.rating  %>
<% end %>

<% if ratings.empty? %>
<% average_rating = 0 %>
<% else %>
<% average_rating = (ratings.reduce(:+)/ratings.size.to_f).round(0)  %>
<% end %>

<div class="right-section">
  <h4 style="text-align: center;">Reviews</h4>
  <div class="meal-review">
    <% @meal.reviews.each do |review| %>
    <div class="card-review">
      <div class="review-name">
        <% if review.user.photo.model[:photo] == nil %>
        <%= image_tag review.user.photo_fake, class: "avatar-review" %>
        <% else %>
        <%= cl_image_tag review.user.photo, class: "avatar-review" %>
        <% end %>
        <p><%= review.user.first_name %></p>
        <p class="review-name-address">Lisboa</p>
      </div>
      <div class="review-body">
        <p class="review-date">
          <% review.rating.times do %>
          <i class="fas fa-star star-yellow"></i>
          <% end %>
          <% (5 - review.rating).times do %>
          <i class="fas fa-star star-grey"></i>
          <% end %>
          <span><%= review.created_at.strftime('%d %b %Y') %></span>
        </p>
        <p>"<em><%= review.content %></em>"</p>
      </div>
    </div>
    <% end %>
  </div>
</div>
</div>

</div>
</div>



<!-- Modal -->
<% if user_signed_in? %>
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Meal added to your cart</h5>
        </div>
        <div class="modal-body">
          <%= @meal.name %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary"><%= link_to "Continue Shopping", meals_path %></button>
          <button type="button" class="btn btn-secondary"><%= link_to "Checkout", order_path(current_user.current_order) %></button>
        </div>
      </div>
    </div>
  </div>
<% end %>
<!-- Modal -->


<script>
  function decrease() {
    let val = document.querySelector(".val");
    if(parseInt(val.value) > parseInt(val.min)) {
      val.value = parseInt(val.value) - 1;
    }
    return val;
  }
  function increase() {
    let val = document.querySelector(".val");
    if(parseInt(val.value) < parseInt(val.max)) {
      val.value = parseInt(val.value) + 1;
    }
    return val;
  }

  const hideElement = (element) => {
    if (element.style.display === "none") {
      element.style.display = "block";
    } else {
      element.style.display = "none";
    }
  }

  const buttonReview = document.getElementById('show-reviews-btn');
  const reviewContainer = document.querySelector('.meal-review');

  buttonReview.addEventListener('click', (event) => {
    hideElement(reviewContainer);
  })
</script>