config/routes.rb
Rails.application.routes.draw do
  get 'carts/show'
  devise_for :users
  root to: 'pages#home'
  get '/cooks', to: 'pages#cooks'
  get '/profile', to: 'pages#profile'
  get "/become_cook", to: "pages#apply"
  get '/confirmation', to: 'orders#confirmation'
  get '/calendar', to: 'pages#calendar'
  get '/users/:id/update', to: 'pages#update', as: :update_user

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :week_days, only: [:new, :create]
  resources :meals do
    resources :reviews, only: [:new, :create]
    resources :items, only: [:new, :create]
    resources :cooks, only: [:show]
  end

  resources :orders, only: [:create, :show] do
    resources :payments, only: [:new, :create]
    resources :items, only: [:destroy]
  end

  resources :dashboard, only: :index

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_order

  def new
  end

  def create
    customer = Stripe::Customer.create(
      source: params[:stripeToken],
      email:  params[:stripeEmail]
    )


    charge = Stripe::Charge.create(
      customer:     customer.id,   # You should store this customer id and re-use it.
      amount:       @order.total_price_cents,
      description:  "Payment for order #{@order.id}",
      currency:     @order.total_price.currency
    )

    @order.update(payment: charge.to_json, status: :paid)
    redirect_to confirmation_path

  rescue Stripe::CardError => e
    flash[:alert] = e.message
    redirect_to confirmation_path

  end

  private

  def set_order
    @order = current_user.orders.pending.find(params[:order_id])
    authorize @order
  end
end

app/views/payments/new.html.erb
<h1>Your order</h1>
<%= form_tag order_payments_path(@order) do %>
  <article>
    <label class="amount">
      <span>Amount: <%= humanized_money_with_symbol(@order.total_price) %></span>
    </label>
  </article>

<!--   #Commented for the lecture, remove comments. -->
  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-name="My Teddy"
    data-email="<%= current_user.email %>"
    data-description="Teddy <%= @order.teddy_sku %>"
    data-amount="<%= @order.amount_cents %>"
    data-currency="<%= @order.amount.currency %>"></script>

<% end %>